### ISSUE TITLE
Authorities Merge stopped working

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#327]
When opening the Merge Authorities tool with duplicate authorities loaded in the multi-record stage, the gaining record selection will only allow the left-hand record to be selected. Attempting to select the right-hand record does not result in an update to the dropdown selection. It's unclear whether this is the reason the Authorities Merge does not work, but no matter what you attempt to select in the dropdown, the merge action triggers a server error.

[2021-12-01 15:34:28,263] ERROR in app: Exception on /api/marc/auths/records/914719/merge [GET]
Traceback (most recent call last):
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/aaron/dev/dlx-rest/dlx_rest/api/__init__.py", line 1113, in get
    changed += update_records(record_type, gaining, losing)
  File "/home/aaron/dev/dlx-rest/dlx_rest/api/__init__.py", line 1092, in update_records
    for record in cls.from_query(query):
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/dlx/marc/__init__.py", line 186, in __next__
    def __next__(self): return next(self.records)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1155, in _refresh
    self.__send_message(q)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/cursor.py", line 1044, in __send_message
    response = client._run_operation(
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1424, in _run_operation
    return self._retryable_read(
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1525, in _retryable_read
    return func(session, server, sock_info, secondary_ok)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1420, in _cmd
    return server.run_operation(
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/server.py", line 130, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/home/aaron/dev/dlx-rest/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: $and/$or/$nor must be a nonempty array, full error: {'ok': 0.0, 'errmsg': '$and/$or/$nor must be a nonempty array', 'code': 2, 'codeName': 'BadValue'}

**Comment by aaronhelton** [comment]
The issue here is that the authorities to be merged should not have been eligible for merging because they were not valid authorities in the first place. This will be fixed with better validations.
